//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace WalshApp.WalshSoap {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WalshSoapSoap", Namespace="http://walshco.elixhosting.com/SVC/")]
    public partial class WalshSoap : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FindDirOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDirOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserPermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveFileDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindObjectIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObjectExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateFileFromBytesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubitemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTemplatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback RenameItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback CopyItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback CleanTempFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback JoinFilesServerOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFilePartOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WalshSoap() {
            this.Url = global::WalshApp.Properties.Settings.Default.WalshApp_com_walshcompany_svc_WalshSoap;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FindDirCompletedEventHandler FindDirCompleted;
        
        /// <remarks/>
        public event CreateDirCompletedEventHandler CreateDirCompleted;
        
        /// <remarks/>
        public event GetUserPermissionsCompletedEventHandler GetUserPermissionsCompleted;
        
        /// <remarks/>
        public event RetrieveFileDataCompletedEventHandler RetrieveFileDataCompleted;
        
        /// <remarks/>
        public event FindObjectIDCompletedEventHandler FindObjectIDCompleted;
        
        /// <remarks/>
        public event ObjectExistsCompletedEventHandler ObjectExistsCompleted;
        
        /// <remarks/>
        public event CreateFileFromBytesCompletedEventHandler CreateFileFromBytesCompleted;
        
        /// <remarks/>
        public event CreateFileCompletedEventHandler CreateFileCompleted;
        
        /// <remarks/>
        public event GetSubitemsCompletedEventHandler GetSubitemsCompleted;
        
        /// <remarks/>
        public event GetTemplatesCompletedEventHandler GetTemplatesCompleted;
        
        /// <remarks/>
        public event GetItemCompletedEventHandler GetItemCompleted;
        
        /// <remarks/>
        public event RenameItemCompletedEventHandler RenameItemCompleted;
        
        /// <remarks/>
        public event DeleteItemCompletedEventHandler DeleteItemCompleted;
        
        /// <remarks/>
        public event CopyItemCompletedEventHandler CopyItemCompleted;
        
        /// <remarks/>
        public event LoginUserCompletedEventHandler LoginUserCompleted;
        
        /// <remarks/>
        public event CleanTempFilesCompletedEventHandler CleanTempFilesCompleted;
        
        /// <remarks/>
        public event JoinFilesServerCompletedEventHandler JoinFilesServerCompleted;
        
        /// <remarks/>
        public event UploadFilePartCompletedEventHandler UploadFilePartCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/FindDir", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public uint FindDir(string userToken, uint parentId, string dirName) {
            object[] results = this.Invoke("FindDir", new object[] {
                        userToken,
                        parentId,
                        dirName});
            return ((uint)(results[0]));
        }
        
        /// <remarks/>
        public void FindDirAsync(string userToken, uint parentId, string dirName) {
            this.FindDirAsync(userToken, parentId, dirName, null);
        }
        
        /// <remarks/>
        public void FindDirAsync(string userToken, uint parentId, string dirName, object userState) {
            if ((this.FindDirOperationCompleted == null)) {
                this.FindDirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindDirOperationCompleted);
            }
            this.InvokeAsync("FindDir", new object[] {
                        userToken,
                        parentId,
                        dirName}, this.FindDirOperationCompleted, userState);
        }
        
        private void OnFindDirOperationCompleted(object arg) {
            if ((this.FindDirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindDirCompleted(this, new FindDirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/CreateDir", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateDir(uint parent_id, string user_token, string name, bool isProject) {
            object[] results = this.Invoke("CreateDir", new object[] {
                        parent_id,
                        user_token,
                        name,
                        isProject});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDirAsync(uint parent_id, string user_token, string name, bool isProject) {
            this.CreateDirAsync(parent_id, user_token, name, isProject, null);
        }
        
        /// <remarks/>
        public void CreateDirAsync(uint parent_id, string user_token, string name, bool isProject, object userState) {
            if ((this.CreateDirOperationCompleted == null)) {
                this.CreateDirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDirOperationCompleted);
            }
            this.InvokeAsync("CreateDir", new object[] {
                        parent_id,
                        user_token,
                        name,
                        isProject}, this.CreateDirOperationCompleted, userState);
        }
        
        private void OnCreateDirOperationCompleted(object arg) {
            if ((this.CreateDirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDirCompleted(this, new CreateDirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/GetUserPermissions", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Permissions GetUserPermissions(string user_token, uint object_id) {
            object[] results = this.Invoke("GetUserPermissions", new object[] {
                        user_token,
                        object_id});
            return ((Permissions)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserPermissionsAsync(string user_token, uint object_id) {
            this.GetUserPermissionsAsync(user_token, object_id, null);
        }
        
        /// <remarks/>
        public void GetUserPermissionsAsync(string user_token, uint object_id, object userState) {
            if ((this.GetUserPermissionsOperationCompleted == null)) {
                this.GetUserPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserPermissionsOperationCompleted);
            }
            this.InvokeAsync("GetUserPermissions", new object[] {
                        user_token,
                        object_id}, this.GetUserPermissionsOperationCompleted, userState);
        }
        
        private void OnGetUserPermissionsOperationCompleted(object arg) {
            if ((this.GetUserPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserPermissionsCompleted(this, new GetUserPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/RetrieveFileData", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FileData RetrieveFileData(string user_token, uint object_id, bool includeBinaryData, bool includeTempUrl) {
            object[] results = this.Invoke("RetrieveFileData", new object[] {
                        user_token,
                        object_id,
                        includeBinaryData,
                        includeTempUrl});
            return ((FileData)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveFileDataAsync(string user_token, uint object_id, bool includeBinaryData, bool includeTempUrl) {
            this.RetrieveFileDataAsync(user_token, object_id, includeBinaryData, includeTempUrl, null);
        }
        
        /// <remarks/>
        public void RetrieveFileDataAsync(string user_token, uint object_id, bool includeBinaryData, bool includeTempUrl, object userState) {
            if ((this.RetrieveFileDataOperationCompleted == null)) {
                this.RetrieveFileDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveFileDataOperationCompleted);
            }
            this.InvokeAsync("RetrieveFileData", new object[] {
                        user_token,
                        object_id,
                        includeBinaryData,
                        includeTempUrl}, this.RetrieveFileDataOperationCompleted, userState);
        }
        
        private void OnRetrieveFileDataOperationCompleted(object arg) {
            if ((this.RetrieveFileDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveFileDataCompleted(this, new RetrieveFileDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/FindObjectID", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public uint FindObjectID(string user_token, string object_name, uint parent_id) {
            object[] results = this.Invoke("FindObjectID", new object[] {
                        user_token,
                        object_name,
                        parent_id});
            return ((uint)(results[0]));
        }
        
        /// <remarks/>
        public void FindObjectIDAsync(string user_token, string object_name, uint parent_id) {
            this.FindObjectIDAsync(user_token, object_name, parent_id, null);
        }
        
        /// <remarks/>
        public void FindObjectIDAsync(string user_token, string object_name, uint parent_id, object userState) {
            if ((this.FindObjectIDOperationCompleted == null)) {
                this.FindObjectIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindObjectIDOperationCompleted);
            }
            this.InvokeAsync("FindObjectID", new object[] {
                        user_token,
                        object_name,
                        parent_id}, this.FindObjectIDOperationCompleted, userState);
        }
        
        private void OnFindObjectIDOperationCompleted(object arg) {
            if ((this.FindObjectIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindObjectIDCompleted(this, new FindObjectIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/ObjectExists", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ObjectExists(uint parent_id, string name) {
            object[] results = this.Invoke("ObjectExists", new object[] {
                        parent_id,
                        name});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ObjectExistsAsync(uint parent_id, string name) {
            this.ObjectExistsAsync(parent_id, name, null);
        }
        
        /// <remarks/>
        public void ObjectExistsAsync(uint parent_id, string name, object userState) {
            if ((this.ObjectExistsOperationCompleted == null)) {
                this.ObjectExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObjectExistsOperationCompleted);
            }
            this.InvokeAsync("ObjectExists", new object[] {
                        parent_id,
                        name}, this.ObjectExistsOperationCompleted, userState);
        }
        
        private void OnObjectExistsOperationCompleted(object arg) {
            if ((this.ObjectExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObjectExistsCompleted(this, new ObjectExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/CreateFileFromBytes", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreateFileData CreateFileFromBytes(uint parent_id, string user_token, string filename, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data, string description) {
            object[] results = this.Invoke("CreateFileFromBytes", new object[] {
                        parent_id,
                        user_token,
                        filename,
                        data,
                        description});
            return ((CreateFileData)(results[0]));
        }
        
        /// <remarks/>
        public void CreateFileFromBytesAsync(uint parent_id, string user_token, string filename, byte[] data, string description) {
            this.CreateFileFromBytesAsync(parent_id, user_token, filename, data, description, null);
        }
        
        /// <remarks/>
        public void CreateFileFromBytesAsync(uint parent_id, string user_token, string filename, byte[] data, string description, object userState) {
            if ((this.CreateFileFromBytesOperationCompleted == null)) {
                this.CreateFileFromBytesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateFileFromBytesOperationCompleted);
            }
            this.InvokeAsync("CreateFileFromBytes", new object[] {
                        parent_id,
                        user_token,
                        filename,
                        data,
                        description}, this.CreateFileFromBytesOperationCompleted, userState);
        }
        
        private void OnCreateFileFromBytesOperationCompleted(object arg) {
            if ((this.CreateFileFromBytesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateFileFromBytesCompleted(this, new CreateFileFromBytesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/CreateFile", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreateFileData CreateFile(uint parent_id, string user_token, string filename, string description, string[] file_parts, string together_checksum) {
            object[] results = this.Invoke("CreateFile", new object[] {
                        parent_id,
                        user_token,
                        filename,
                        description,
                        file_parts,
                        together_checksum});
            return ((CreateFileData)(results[0]));
        }
        
        /// <remarks/>
        public void CreateFileAsync(uint parent_id, string user_token, string filename, string description, string[] file_parts, string together_checksum) {
            this.CreateFileAsync(parent_id, user_token, filename, description, file_parts, together_checksum, null);
        }
        
        /// <remarks/>
        public void CreateFileAsync(uint parent_id, string user_token, string filename, string description, string[] file_parts, string together_checksum, object userState) {
            if ((this.CreateFileOperationCompleted == null)) {
                this.CreateFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateFileOperationCompleted);
            }
            this.InvokeAsync("CreateFile", new object[] {
                        parent_id,
                        user_token,
                        filename,
                        description,
                        file_parts,
                        together_checksum}, this.CreateFileOperationCompleted, userState);
        }
        
        private void OnCreateFileOperationCompleted(object arg) {
            if ((this.CreateFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateFileCompleted(this, new CreateFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/GetSubitems", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObjectTreeData[] GetSubitems(uint parent_id, string user_token) {
            object[] results = this.Invoke("GetSubitems", new object[] {
                        parent_id,
                        user_token});
            return ((ObjectTreeData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSubitemsAsync(uint parent_id, string user_token) {
            this.GetSubitemsAsync(parent_id, user_token, null);
        }
        
        /// <remarks/>
        public void GetSubitemsAsync(uint parent_id, string user_token, object userState) {
            if ((this.GetSubitemsOperationCompleted == null)) {
                this.GetSubitemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubitemsOperationCompleted);
            }
            this.InvokeAsync("GetSubitems", new object[] {
                        parent_id,
                        user_token}, this.GetSubitemsOperationCompleted, userState);
        }
        
        private void OnGetSubitemsOperationCompleted(object arg) {
            if ((this.GetSubitemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubitemsCompleted(this, new GetSubitemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/GetTemplates", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObjectTreeData[] GetTemplates(string user_token) {
            object[] results = this.Invoke("GetTemplates", new object[] {
                        user_token});
            return ((ObjectTreeData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTemplatesAsync(string user_token) {
            this.GetTemplatesAsync(user_token, null);
        }
        
        /// <remarks/>
        public void GetTemplatesAsync(string user_token, object userState) {
            if ((this.GetTemplatesOperationCompleted == null)) {
                this.GetTemplatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTemplatesOperationCompleted);
            }
            this.InvokeAsync("GetTemplates", new object[] {
                        user_token}, this.GetTemplatesOperationCompleted, userState);
        }
        
        private void OnGetTemplatesOperationCompleted(object arg) {
            if ((this.GetTemplatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTemplatesCompleted(this, new GetTemplatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/GetItem", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObjectTreeData GetItem(string user_token, uint object_id) {
            object[] results = this.Invoke("GetItem", new object[] {
                        user_token,
                        object_id});
            return ((ObjectTreeData)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemAsync(string user_token, uint object_id) {
            this.GetItemAsync(user_token, object_id, null);
        }
        
        /// <remarks/>
        public void GetItemAsync(string user_token, uint object_id, object userState) {
            if ((this.GetItemOperationCompleted == null)) {
                this.GetItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemOperationCompleted);
            }
            this.InvokeAsync("GetItem", new object[] {
                        user_token,
                        object_id}, this.GetItemOperationCompleted, userState);
        }
        
        private void OnGetItemOperationCompleted(object arg) {
            if ((this.GetItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemCompleted(this, new GetItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/RenameItem", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RenameItem(string user_token, uint parent_id, string old_name, string new_name) {
            object[] results = this.Invoke("RenameItem", new object[] {
                        user_token,
                        parent_id,
                        old_name,
                        new_name});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RenameItemAsync(string user_token, uint parent_id, string old_name, string new_name) {
            this.RenameItemAsync(user_token, parent_id, old_name, new_name, null);
        }
        
        /// <remarks/>
        public void RenameItemAsync(string user_token, uint parent_id, string old_name, string new_name, object userState) {
            if ((this.RenameItemOperationCompleted == null)) {
                this.RenameItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRenameItemOperationCompleted);
            }
            this.InvokeAsync("RenameItem", new object[] {
                        user_token,
                        parent_id,
                        old_name,
                        new_name}, this.RenameItemOperationCompleted, userState);
        }
        
        private void OnRenameItemOperationCompleted(object arg) {
            if ((this.RenameItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RenameItemCompleted(this, new RenameItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/DeleteItem", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteItem(string user_token, uint parent_id, string object_name) {
            object[] results = this.Invoke("DeleteItem", new object[] {
                        user_token,
                        parent_id,
                        object_name});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteItemAsync(string user_token, uint parent_id, string object_name) {
            this.DeleteItemAsync(user_token, parent_id, object_name, null);
        }
        
        /// <remarks/>
        public void DeleteItemAsync(string user_token, uint parent_id, string object_name, object userState) {
            if ((this.DeleteItemOperationCompleted == null)) {
                this.DeleteItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteItemOperationCompleted);
            }
            this.InvokeAsync("DeleteItem", new object[] {
                        user_token,
                        parent_id,
                        object_name}, this.DeleteItemOperationCompleted, userState);
        }
        
        private void OnDeleteItemOperationCompleted(object arg) {
            if ((this.DeleteItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteItemCompleted(this, new DeleteItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/CopyItem", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CopyItem(string user_token, uint object_id, uint destination_parent, bool copyItemSelf) {
            object[] results = this.Invoke("CopyItem", new object[] {
                        user_token,
                        object_id,
                        destination_parent,
                        copyItemSelf});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CopyItemAsync(string user_token, uint object_id, uint destination_parent, bool copyItemSelf) {
            this.CopyItemAsync(user_token, object_id, destination_parent, copyItemSelf, null);
        }
        
        /// <remarks/>
        public void CopyItemAsync(string user_token, uint object_id, uint destination_parent, bool copyItemSelf, object userState) {
            if ((this.CopyItemOperationCompleted == null)) {
                this.CopyItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCopyItemOperationCompleted);
            }
            this.InvokeAsync("CopyItem", new object[] {
                        user_token,
                        object_id,
                        destination_parent,
                        copyItemSelf}, this.CopyItemOperationCompleted, userState);
        }
        
        private void OnCopyItemOperationCompleted(object arg) {
            if ((this.CopyItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CopyItemCompleted(this, new CopyItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/LoginUser", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoginUser(string username, string password) {
            object[] results = this.Invoke("LoginUser", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginUserAsync(string username, string password) {
            this.LoginUserAsync(username, password, null);
        }
        
        /// <remarks/>
        public void LoginUserAsync(string username, string password, object userState) {
            if ((this.LoginUserOperationCompleted == null)) {
                this.LoginUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginUserOperationCompleted);
            }
            this.InvokeAsync("LoginUser", new object[] {
                        username,
                        password}, this.LoginUserOperationCompleted, userState);
        }
        
        private void OnLoginUserOperationCompleted(object arg) {
            if ((this.LoginUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginUserCompleted(this, new LoginUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/CleanTempFiles", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CleanTempFiles() {
            this.Invoke("CleanTempFiles", new object[0]);
        }
        
        /// <remarks/>
        public void CleanTempFilesAsync() {
            this.CleanTempFilesAsync(null);
        }
        
        /// <remarks/>
        public void CleanTempFilesAsync(object userState) {
            if ((this.CleanTempFilesOperationCompleted == null)) {
                this.CleanTempFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCleanTempFilesOperationCompleted);
            }
            this.InvokeAsync("CleanTempFiles", new object[0], this.CleanTempFilesOperationCompleted, userState);
        }
        
        private void OnCleanTempFilesOperationCompleted(object arg) {
            if ((this.CleanTempFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CleanTempFilesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/JoinFilesServer", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string JoinFilesServer(string[] file_part_guids, string together_checksum) {
            object[] results = this.Invoke("JoinFilesServer", new object[] {
                        file_part_guids,
                        together_checksum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void JoinFilesServerAsync(string[] file_part_guids, string together_checksum) {
            this.JoinFilesServerAsync(file_part_guids, together_checksum, null);
        }
        
        /// <remarks/>
        public void JoinFilesServerAsync(string[] file_part_guids, string together_checksum, object userState) {
            if ((this.JoinFilesServerOperationCompleted == null)) {
                this.JoinFilesServerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJoinFilesServerOperationCompleted);
            }
            this.InvokeAsync("JoinFilesServer", new object[] {
                        file_part_guids,
                        together_checksum}, this.JoinFilesServerOperationCompleted, userState);
        }
        
        private void OnJoinFilesServerOperationCompleted(object arg) {
            if ((this.JoinFilesServerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JoinFilesServerCompleted(this, new JoinFilesServerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/UploadFilePart", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadFilePart([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] file_data, string checksum) {
            object[] results = this.Invoke("UploadFilePart", new object[] {
                        file_data,
                        checksum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFilePartAsync(byte[] file_data, string checksum) {
            this.UploadFilePartAsync(file_data, checksum, null);
        }
        
        /// <remarks/>
        public void UploadFilePartAsync(byte[] file_data, string checksum, object userState) {
            if ((this.UploadFilePartOperationCompleted == null)) {
                this.UploadFilePartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFilePartOperationCompleted);
            }
            this.InvokeAsync("UploadFilePart", new object[] {
                        file_data,
                        checksum}, this.UploadFilePartOperationCompleted, userState);
        }
        
        private void OnUploadFilePartOperationCompleted(object arg) {
            if ((this.UploadFilePartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFilePartCompleted(this, new UploadFilePartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walshco.elixhosting.com/SVC/")]
    public partial class Permissions {
        
        private string displayNameField;
        
        private uint object_idField;
        
        private uint accessor_idField;
        
        private Access readFileField;
        
        private Access writeFileField;
        
        private Access viewInfoField;
        
        private Access commentField;
        
        private Access readHistoricalField;
        
        private Access manageHistoricalField;
        
        private Access renameField;
        
        private Access deleteField;
        
        private Access copyField;
        
        private Access changePermissionsField;
        
        private Access changeOwnerField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public uint object_id {
            get {
                return this.object_idField;
            }
            set {
                this.object_idField = value;
            }
        }
        
        /// <remarks/>
        public uint accessor_id {
            get {
                return this.accessor_idField;
            }
            set {
                this.accessor_idField = value;
            }
        }
        
        /// <remarks/>
        public Access ReadFile {
            get {
                return this.readFileField;
            }
            set {
                this.readFileField = value;
            }
        }
        
        /// <remarks/>
        public Access WriteFile {
            get {
                return this.writeFileField;
            }
            set {
                this.writeFileField = value;
            }
        }
        
        /// <remarks/>
        public Access ViewInfo {
            get {
                return this.viewInfoField;
            }
            set {
                this.viewInfoField = value;
            }
        }
        
        /// <remarks/>
        public Access Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public Access ReadHistorical {
            get {
                return this.readHistoricalField;
            }
            set {
                this.readHistoricalField = value;
            }
        }
        
        /// <remarks/>
        public Access ManageHistorical {
            get {
                return this.manageHistoricalField;
            }
            set {
                this.manageHistoricalField = value;
            }
        }
        
        /// <remarks/>
        public Access Rename {
            get {
                return this.renameField;
            }
            set {
                this.renameField = value;
            }
        }
        
        /// <remarks/>
        public Access Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        public Access Copy {
            get {
                return this.copyField;
            }
            set {
                this.copyField = value;
            }
        }
        
        /// <remarks/>
        public Access ChangePermissions {
            get {
                return this.changePermissionsField;
            }
            set {
                this.changePermissionsField = value;
            }
        }
        
        /// <remarks/>
        public Access ChangeOwner {
            get {
                return this.changeOwnerField;
            }
            set {
                this.changeOwnerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walshco.elixhosting.com/SVC/")]
    public enum Access {
        
        /// <remarks/>
        Allow,
        
        /// <remarks/>
        Deny,
        
        /// <remarks/>
        Inherit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walshco.elixhosting.com/SVC/")]
    public partial class ObjectTreeData {
        
        private uint object_idField;
        
        private uint parent_object_idField;
        
        private uint object_typeField;
        
        private string object_descriptionField;
        
        private string object_serverField;
        
        private string object_bucketField;
        
        private string object_keyField;
        
        private uint object_sizeField;
        
        private System.DateTime revision_dateField;
        
        private uint child_countField;
        
        private string object_nameField;
        
        /// <remarks/>
        public uint object_id {
            get {
                return this.object_idField;
            }
            set {
                this.object_idField = value;
            }
        }
        
        /// <remarks/>
        public uint parent_object_id {
            get {
                return this.parent_object_idField;
            }
            set {
                this.parent_object_idField = value;
            }
        }
        
        /// <remarks/>
        public uint object_type {
            get {
                return this.object_typeField;
            }
            set {
                this.object_typeField = value;
            }
        }
        
        /// <remarks/>
        public string object_description {
            get {
                return this.object_descriptionField;
            }
            set {
                this.object_descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string object_server {
            get {
                return this.object_serverField;
            }
            set {
                this.object_serverField = value;
            }
        }
        
        /// <remarks/>
        public string object_bucket {
            get {
                return this.object_bucketField;
            }
            set {
                this.object_bucketField = value;
            }
        }
        
        /// <remarks/>
        public string object_key {
            get {
                return this.object_keyField;
            }
            set {
                this.object_keyField = value;
            }
        }
        
        /// <remarks/>
        public uint object_size {
            get {
                return this.object_sizeField;
            }
            set {
                this.object_sizeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime revision_date {
            get {
                return this.revision_dateField;
            }
            set {
                this.revision_dateField = value;
            }
        }
        
        /// <remarks/>
        public uint child_count {
            get {
                return this.child_countField;
            }
            set {
                this.child_countField = value;
            }
        }
        
        /// <remarks/>
        public string object_name {
            get {
                return this.object_nameField;
            }
            set {
                this.object_nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walshco.elixhosting.com/SVC/")]
    public partial class CreateFileData {
        
        private string file_nameField;
        
        private uint object_typeField;
        
        private uint object_idField;
        
        /// <remarks/>
        public string file_name {
            get {
                return this.file_nameField;
            }
            set {
                this.file_nameField = value;
            }
        }
        
        /// <remarks/>
        public uint object_type {
            get {
                return this.object_typeField;
            }
            set {
                this.object_typeField = value;
            }
        }
        
        /// <remarks/>
        public uint object_id {
            get {
                return this.object_idField;
            }
            set {
                this.object_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walshco.elixhosting.com/SVC/")]
    public partial class FileData {
        
        private uint parentIdField;
        
        private string objectNameField;
        
        private byte[] dataField;
        
        private string descriptionField;
        
        private uint objectTypeField;
        
        private System.DateTime revisionDateField;
        
        private string tempURLField;
        
        /// <remarks/>
        public uint parentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        public string objectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public uint objectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime revisionDate {
            get {
                return this.revisionDateField;
            }
            set {
                this.revisionDateField = value;
            }
        }
        
        /// <remarks/>
        public string tempURL {
            get {
                return this.tempURLField;
            }
            set {
                this.tempURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void FindDirCompletedEventHandler(object sender, FindDirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindDirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindDirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public uint Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((uint)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CreateDirCompletedEventHandler(object sender, CreateDirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetUserPermissionsCompletedEventHandler(object sender, GetUserPermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Permissions Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Permissions)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void RetrieveFileDataCompletedEventHandler(object sender, RetrieveFileDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveFileDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveFileDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FileData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FileData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void FindObjectIDCompletedEventHandler(object sender, FindObjectIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindObjectIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindObjectIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public uint Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((uint)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ObjectExistsCompletedEventHandler(object sender, ObjectExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObjectExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObjectExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CreateFileFromBytesCompletedEventHandler(object sender, CreateFileFromBytesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateFileFromBytesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateFileFromBytesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateFileData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateFileData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CreateFileCompletedEventHandler(object sender, CreateFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateFileData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateFileData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetSubitemsCompletedEventHandler(object sender, GetSubitemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubitemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubitemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjectTreeData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjectTreeData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetTemplatesCompletedEventHandler(object sender, GetTemplatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTemplatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTemplatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjectTreeData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjectTreeData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetItemCompletedEventHandler(object sender, GetItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjectTreeData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjectTreeData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void RenameItemCompletedEventHandler(object sender, RenameItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RenameItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RenameItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void DeleteItemCompletedEventHandler(object sender, DeleteItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CopyItemCompletedEventHandler(object sender, CopyItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CopyItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CopyItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void LoginUserCompletedEventHandler(object sender, LoginUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CleanTempFilesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void JoinFilesServerCompletedEventHandler(object sender, JoinFilesServerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JoinFilesServerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JoinFilesServerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UploadFilePartCompletedEventHandler(object sender, UploadFilePartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFilePartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFilePartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591