//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace Walsh.Shared.WalshSoap {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WalshSoapSoap", Namespace="http://walshco.elixhosting.com/SVC/")]
    public partial class WalshSoap : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateDirOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserPermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveFileDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindObjectIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubitemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTemplatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WalshSoap() {
            this.Url = global::Walsh.Shared.Properties.Settings.Default.Walsh_Shared_WalshSoap_WalshSoap;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateDirCompletedEventHandler CreateDirCompleted;
        
        /// <remarks/>
        public event GetUserPermissionsCompletedEventHandler GetUserPermissionsCompleted;
        
        /// <remarks/>
        public event RetrieveFileDataCompletedEventHandler RetrieveFileDataCompleted;
        
        /// <remarks/>
        public event FindObjectIDCompletedEventHandler FindObjectIDCompleted;
        
        /// <remarks/>
        public event CreateFileCompletedEventHandler CreateFileCompleted;
        
        /// <remarks/>
        public event GetSubitemsCompletedEventHandler GetSubitemsCompleted;
        
        /// <remarks/>
        public event GetTemplatesCompletedEventHandler GetTemplatesCompleted;
        
        /// <remarks/>
        public event GetItemCompletedEventHandler GetItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/CreateDir", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateDir(uint parent_id, string user_token, string name) {
            object[] results = this.Invoke("CreateDir", new object[] {
                        parent_id,
                        user_token,
                        name});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDirAsync(uint parent_id, string user_token, string name) {
            this.CreateDirAsync(parent_id, user_token, name, null);
        }
        
        /// <remarks/>
        public void CreateDirAsync(uint parent_id, string user_token, string name, object userState) {
            if ((this.CreateDirOperationCompleted == null)) {
                this.CreateDirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDirOperationCompleted);
            }
            this.InvokeAsync("CreateDir", new object[] {
                        parent_id,
                        user_token,
                        name}, this.CreateDirOperationCompleted, userState);
        }
        
        private void OnCreateDirOperationCompleted(object arg) {
            if ((this.CreateDirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDirCompleted(this, new CreateDirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/GetUserPermissions", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Permissions GetUserPermissions(string user_token, uint object_id) {
            object[] results = this.Invoke("GetUserPermissions", new object[] {
                        user_token,
                        object_id});
            return ((Permissions)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserPermissionsAsync(string user_token, uint object_id) {
            this.GetUserPermissionsAsync(user_token, object_id, null);
        }
        
        /// <remarks/>
        public void GetUserPermissionsAsync(string user_token, uint object_id, object userState) {
            if ((this.GetUserPermissionsOperationCompleted == null)) {
                this.GetUserPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserPermissionsOperationCompleted);
            }
            this.InvokeAsync("GetUserPermissions", new object[] {
                        user_token,
                        object_id}, this.GetUserPermissionsOperationCompleted, userState);
        }
        
        private void OnGetUserPermissionsOperationCompleted(object arg) {
            if ((this.GetUserPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserPermissionsCompleted(this, new GetUserPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/RetrieveFileData", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FileData RetrieveFileData(string user_token, uint object_id, bool includeBinaryData, bool includeTempUrl) {
            object[] results = this.Invoke("RetrieveFileData", new object[] {
                        user_token,
                        object_id,
                        includeBinaryData,
                        includeTempUrl});
            return ((FileData)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveFileDataAsync(string user_token, uint object_id, bool includeBinaryData, bool includeTempUrl) {
            this.RetrieveFileDataAsync(user_token, object_id, includeBinaryData, includeTempUrl, null);
        }
        
        /// <remarks/>
        public void RetrieveFileDataAsync(string user_token, uint object_id, bool includeBinaryData, bool includeTempUrl, object userState) {
            if ((this.RetrieveFileDataOperationCompleted == null)) {
                this.RetrieveFileDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveFileDataOperationCompleted);
            }
            this.InvokeAsync("RetrieveFileData", new object[] {
                        user_token,
                        object_id,
                        includeBinaryData,
                        includeTempUrl}, this.RetrieveFileDataOperationCompleted, userState);
        }
        
        private void OnRetrieveFileDataOperationCompleted(object arg) {
            if ((this.RetrieveFileDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveFileDataCompleted(this, new RetrieveFileDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/FindObjectID", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public uint FindObjectID(string user_token, string object_name, uint parent_id) {
            object[] results = this.Invoke("FindObjectID", new object[] {
                        user_token,
                        object_name,
                        parent_id});
            return ((uint)(results[0]));
        }
        
        /// <remarks/>
        public void FindObjectIDAsync(string user_token, string object_name, uint parent_id) {
            this.FindObjectIDAsync(user_token, object_name, parent_id, null);
        }
        
        /// <remarks/>
        public void FindObjectIDAsync(string user_token, string object_name, uint parent_id, object userState) {
            if ((this.FindObjectIDOperationCompleted == null)) {
                this.FindObjectIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindObjectIDOperationCompleted);
            }
            this.InvokeAsync("FindObjectID", new object[] {
                        user_token,
                        object_name,
                        parent_id}, this.FindObjectIDOperationCompleted, userState);
        }
        
        private void OnFindObjectIDOperationCompleted(object arg) {
            if ((this.FindObjectIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindObjectIDCompleted(this, new FindObjectIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/CreateFile", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreateFileData CreateFile(uint parent_id, string user_token, string filename, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data, string description) {
            object[] results = this.Invoke("CreateFile", new object[] {
                        parent_id,
                        user_token,
                        filename,
                        data,
                        description});
            return ((CreateFileData)(results[0]));
        }
        
        /// <remarks/>
        public void CreateFileAsync(uint parent_id, string user_token, string filename, byte[] data, string description) {
            this.CreateFileAsync(parent_id, user_token, filename, data, description, null);
        }
        
        /// <remarks/>
        public void CreateFileAsync(uint parent_id, string user_token, string filename, byte[] data, string description, object userState) {
            if ((this.CreateFileOperationCompleted == null)) {
                this.CreateFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateFileOperationCompleted);
            }
            this.InvokeAsync("CreateFile", new object[] {
                        parent_id,
                        user_token,
                        filename,
                        data,
                        description}, this.CreateFileOperationCompleted, userState);
        }
        
        private void OnCreateFileOperationCompleted(object arg) {
            if ((this.CreateFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateFileCompleted(this, new CreateFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/GetSubitems", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObjectTreeData[] GetSubitems(uint parent_id, string user_token) {
            object[] results = this.Invoke("GetSubitems", new object[] {
                        parent_id,
                        user_token});
            return ((ObjectTreeData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSubitemsAsync(uint parent_id, string user_token) {
            this.GetSubitemsAsync(parent_id, user_token, null);
        }
        
        /// <remarks/>
        public void GetSubitemsAsync(uint parent_id, string user_token, object userState) {
            if ((this.GetSubitemsOperationCompleted == null)) {
                this.GetSubitemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubitemsOperationCompleted);
            }
            this.InvokeAsync("GetSubitems", new object[] {
                        parent_id,
                        user_token}, this.GetSubitemsOperationCompleted, userState);
        }
        
        private void OnGetSubitemsOperationCompleted(object arg) {
            if ((this.GetSubitemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubitemsCompleted(this, new GetSubitemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/GetTemplates", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObjectTreeData[] GetTemplates(string user_token) {
            object[] results = this.Invoke("GetTemplates", new object[] {
                        user_token});
            return ((ObjectTreeData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTemplatesAsync(string user_token) {
            this.GetTemplatesAsync(user_token, null);
        }
        
        /// <remarks/>
        public void GetTemplatesAsync(string user_token, object userState) {
            if ((this.GetTemplatesOperationCompleted == null)) {
                this.GetTemplatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTemplatesOperationCompleted);
            }
            this.InvokeAsync("GetTemplates", new object[] {
                        user_token}, this.GetTemplatesOperationCompleted, userState);
        }
        
        private void OnGetTemplatesOperationCompleted(object arg) {
            if ((this.GetTemplatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTemplatesCompleted(this, new GetTemplatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://walshco.elixhosting.com/SVC/GetItem", RequestNamespace="http://walshco.elixhosting.com/SVC/", ResponseNamespace="http://walshco.elixhosting.com/SVC/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObjectTreeData GetItem(string user_token, uint object_id) {
            object[] results = this.Invoke("GetItem", new object[] {
                        user_token,
                        object_id});
            return ((ObjectTreeData)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemAsync(string user_token, uint object_id) {
            this.GetItemAsync(user_token, object_id, null);
        }
        
        /// <remarks/>
        public void GetItemAsync(string user_token, uint object_id, object userState) {
            if ((this.GetItemOperationCompleted == null)) {
                this.GetItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemOperationCompleted);
            }
            this.InvokeAsync("GetItem", new object[] {
                        user_token,
                        object_id}, this.GetItemOperationCompleted, userState);
        }
        
        private void OnGetItemOperationCompleted(object arg) {
            if ((this.GetItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemCompleted(this, new GetItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walshco.elixhosting.com/SVC/")]
    public partial class Permissions {
        
        private string accessorNameField;
        
        private bool canReadFileField;
        
        private bool canWriteFileField;
        
        private bool canViewInfoField;
        
        private bool canCommentField;
        
        private bool canReadHistoricalField;
        
        private bool canManageHistoricalField;
        
        private bool canRenameField;
        
        private bool canDeleteField;
        
        private bool canCopyField;
        
        private bool canChangePermissionsField;
        
        private bool canChangeOwnerField;
        
        /// <remarks/>
        public string AccessorName {
            get {
                return this.accessorNameField;
            }
            set {
                this.accessorNameField = value;
            }
        }
        
        /// <remarks/>
        public bool CanReadFile {
            get {
                return this.canReadFileField;
            }
            set {
                this.canReadFileField = value;
            }
        }
        
        /// <remarks/>
        public bool CanWriteFile {
            get {
                return this.canWriteFileField;
            }
            set {
                this.canWriteFileField = value;
            }
        }
        
        /// <remarks/>
        public bool CanViewInfo {
            get {
                return this.canViewInfoField;
            }
            set {
                this.canViewInfoField = value;
            }
        }
        
        /// <remarks/>
        public bool CanComment {
            get {
                return this.canCommentField;
            }
            set {
                this.canCommentField = value;
            }
        }
        
        /// <remarks/>
        public bool CanReadHistorical {
            get {
                return this.canReadHistoricalField;
            }
            set {
                this.canReadHistoricalField = value;
            }
        }
        
        /// <remarks/>
        public bool CanManageHistorical {
            get {
                return this.canManageHistoricalField;
            }
            set {
                this.canManageHistoricalField = value;
            }
        }
        
        /// <remarks/>
        public bool CanRename {
            get {
                return this.canRenameField;
            }
            set {
                this.canRenameField = value;
            }
        }
        
        /// <remarks/>
        public bool CanDelete {
            get {
                return this.canDeleteField;
            }
            set {
                this.canDeleteField = value;
            }
        }
        
        /// <remarks/>
        public bool CanCopy {
            get {
                return this.canCopyField;
            }
            set {
                this.canCopyField = value;
            }
        }
        
        /// <remarks/>
        public bool CanChangePermissions {
            get {
                return this.canChangePermissionsField;
            }
            set {
                this.canChangePermissionsField = value;
            }
        }
        
        /// <remarks/>
        public bool CanChangeOwner {
            get {
                return this.canChangeOwnerField;
            }
            set {
                this.canChangeOwnerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walshco.elixhosting.com/SVC/")]
    public partial class ObjectTreeData {
        
        private uint object_idField;
        
        private uint parent_object_idField;
        
        private uint object_typeField;
        
        private string object_nameField;
        
        private string object_descriptionField;
        
        private string object_serverField;
        
        private string object_bucketField;
        
        private string object_keyField;
        
        private uint object_sizeField;
        
        private System.DateTime revision_dateField;
        
        private uint child_countField;
        
        /// <remarks/>
        public uint object_id {
            get {
                return this.object_idField;
            }
            set {
                this.object_idField = value;
            }
        }
        
        /// <remarks/>
        public uint parent_object_id {
            get {
                return this.parent_object_idField;
            }
            set {
                this.parent_object_idField = value;
            }
        }
        
        /// <remarks/>
        public uint object_type {
            get {
                return this.object_typeField;
            }
            set {
                this.object_typeField = value;
            }
        }
        
        /// <remarks/>
        public string object_name {
            get {
                return this.object_nameField;
            }
            set {
                this.object_nameField = value;
            }
        }
        
        /// <remarks/>
        public string object_description {
            get {
                return this.object_descriptionField;
            }
            set {
                this.object_descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string object_server {
            get {
                return this.object_serverField;
            }
            set {
                this.object_serverField = value;
            }
        }
        
        /// <remarks/>
        public string object_bucket {
            get {
                return this.object_bucketField;
            }
            set {
                this.object_bucketField = value;
            }
        }
        
        /// <remarks/>
        public string object_key {
            get {
                return this.object_keyField;
            }
            set {
                this.object_keyField = value;
            }
        }
        
        /// <remarks/>
        public uint object_size {
            get {
                return this.object_sizeField;
            }
            set {
                this.object_sizeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime revision_date {
            get {
                return this.revision_dateField;
            }
            set {
                this.revision_dateField = value;
            }
        }
        
        /// <remarks/>
        public uint child_count {
            get {
                return this.child_countField;
            }
            set {
                this.child_countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walshco.elixhosting.com/SVC/")]
    public partial class CreateFileData {
        
        private string file_nameField;
        
        private uint object_typeField;
        
        private uint object_idField;
        
        /// <remarks/>
        public string file_name {
            get {
                return this.file_nameField;
            }
            set {
                this.file_nameField = value;
            }
        }
        
        /// <remarks/>
        public uint object_type {
            get {
                return this.object_typeField;
            }
            set {
                this.object_typeField = value;
            }
        }
        
        /// <remarks/>
        public uint object_id {
            get {
                return this.object_idField;
            }
            set {
                this.object_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://walshco.elixhosting.com/SVC/")]
    public partial class FileData {
        
        private uint parentIdField;
        
        private string objectNameField;
        
        private byte[] dataField;
        
        private string descriptionField;
        
        private uint objectTypeField;
        
        private System.DateTime revisionDateField;
        
        private string tempURLField;
        
        /// <remarks/>
        public uint parentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        public string objectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public uint objectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime revisionDate {
            get {
                return this.revisionDateField;
            }
            set {
                this.revisionDateField = value;
            }
        }
        
        /// <remarks/>
        public string tempURL {
            get {
                return this.tempURLField;
            }
            set {
                this.tempURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateDirCompletedEventHandler(object sender, CreateDirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetUserPermissionsCompletedEventHandler(object sender, GetUserPermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Permissions Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Permissions)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void RetrieveFileDataCompletedEventHandler(object sender, RetrieveFileDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveFileDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveFileDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FileData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FileData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void FindObjectIDCompletedEventHandler(object sender, FindObjectIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindObjectIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindObjectIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public uint Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((uint)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateFileCompletedEventHandler(object sender, CreateFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateFileData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateFileData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetSubitemsCompletedEventHandler(object sender, GetSubitemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubitemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubitemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjectTreeData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjectTreeData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetTemplatesCompletedEventHandler(object sender, GetTemplatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTemplatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTemplatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjectTreeData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjectTreeData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetItemCompletedEventHandler(object sender, GetItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjectTreeData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjectTreeData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591